%RESAVE Resave workspace.
%   RESAVE reformats the variables in the file './temp.mat', which should 
%   refer to a .mat file automatically generated by savemat.py. All values 
%   are recast as doubles, and multidimensional matrices are resaved as 
%   cells along the time axes such that each variable can be consistently 
%   called according to its frame number. Vectors are all resaved as columns.

%   Charlie Wright, 2012-10-16
%   charles.s.wright@gmail.com

% Load the saved variables from file and create new structure to save back
fileName = 'D:\AB_PyCelegans\N2_150313\N2_150313.mat';
W = load(fileName);
Y = [];

% Find number of frames
Y.frames = double(W.('frames'));
n = numel(Y.frames);

% Loop over remaining variables
fs = setdiff(fieldnames(W), 'frames');
for i = 1:length(fs)
    f = fs{i};
    
    if iscell(W.(f))
        Y.(f) = cellfun(@double, W.(f), 'Uni', 0);
        continue
    end
    
    % Make vector of dimensions, excluding time axis
    x = double(W.(f));
    d = 1:ndims(x);
    s = size(x);
    d(find(s==n, 1, 'first')) = [];
    
    % Convert to cell at each frame if would not leave singleton value
    if s(d) > 1
        x = cellfun(@squeeze, num2cell(x, [2 3]), 'Uni', 0);
        
        % Convert all vectors to columns
        for j = 1:n
            if any(size(x{j}, 1) == [1, 2])
                x{j} = x{j}';
            end
        end
    end
    
    Y.(f) = x;
end

% Save in place, overwriting original variables
save(fileName, '-struct', 'Y')