#!/usr/bin/env python
########################################################################
#  Author: Nicholas Labello, labello@uchicago.edu
#  The University of Chicago Research Computing Center
########################################################################
'''
==================
creatediffimage
==================
This stand alone executable builds a new image with the following
operation.

  ((background - image) > THRESH) * image  

*background* will be approximately equally bright as *image* on every
pixel that the worm does not occupy in *image* (roughly +/- 10 based on 
0-255 range possible with 8 bit grayscale images).  

Pixels that the worm occupies will be substantially darker (lower) in *image* 
than background, by an intensity of 20 or more.  The image that is segmented 
and used for analysis is generated by the following steps.

1.  subtract *image* from *background*, result 8 bit array
        tempimage = background - image

2.  generate binary array where *tempimage* is greater than THRESH
        temp2image = tempimage > THRESH

3.  multiply *temp2image* by *image*.  
        finalimage = temp2image * image

As a result, if THRESH is chosen well, *finalimage* will contain only one major 
object, the worm.  Segmentation and analysis of *finalimage* results in vastly
cleaner identification of worm head/tail/border than segmentation/analysis of 

* Usage:  creatediffimage.py [background.jpg] [image.jpg] [THRESH]

'''

import sys
import scipy.misc

def main():
    Background = scipy.misc.imread(sys.argv[1])
    Image = scipy.misc.imread(sys.argv[2])
    thresh = int(sys.argv[3])
    DiffImage = ( (Background - Image) > thresh ) * Image
    scipy.misc.imsave("diffimage"+str(thresh)+".jpg",DiffImage)

if __name__ == '__main__':
    if (len(sys.argv)) != 4:
        print "Usage:  creatediffimage.py [background.jpg] [image.jpg] [THRESH]"
        sys.exit()

    main()
